# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='bank',
            new_name='branch',
        ),
    ]
