# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180411_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_arrived', models.DateTimeField(auto_now=True)),
                ('last_arrived', models.DateTimeField(auto_now_add=True)),
                ('total_balance', models.IntegerField(default=0)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('banks', models.ManyToManyField(blank=True, through='demo.BanksInfo', to='demo.Bank')),
            ],
        ),
        migrations.AddField(
            model_name='banksinfo',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Customer'),
        ),
    ]
